//! Conformance test: the hardcoded ECU pit-diag decoder vs. the ECU DBC.
//!
//! Sibling of `pitdiag_dbc_conformance.rs`, which does the same job for
//! the AMS. `src/pit_diag/ecu.rs` decodes the ECU stream from a
//! **hardcoded** layout — fixed IDs, byte offsets, bit positions,
//! endianness and enum tables — against a wire that is generated from a
//! DSL in another repo (`IFS08-CE-ECU`, `Core/Inc/can/messages/*.def` →
//! `docs/dbc/ecu.dbc`, regenerated by their dbcinator bot).
//!
//! Nothing enforced that the two stayed in sync, and they didn't. By the
//! time #528 was filed, **six** drifts had accumulated silently:
//!
//! - `inv_mode_cmd` (`0x702` bits 57-63) never decoded at all;
//! - `EcuInvState` naming 2 of the 7 values the DSL defines, so every
//!   fault state rendered as `unknown(0x..)`;
//! - `0x704` `reset_cause` read as a whole byte after the firmware
//!   narrowed it to 3 bits, so a `stub_brake` board reported an
//!   impossible reset cause;
//! - `0x704` `task_diag` read at bit 3 after TelemetryTask took that bit,
//!   so the "diag alive" indicator showed the *telemetry* task;
//! - `0x704` bits 37-39 (the bench-stub announces) dropped entirely;
//! - `0x700` `tx_dropped` (bit 22) never decoded.
//!
//! The first five were fixed in v2.9.0 by hand. This test is what makes
//! the *next* one loud, and it is deliberately stricter than the AMS
//! sibling in one way that matters: [`signal_layouts_match_the_decoder`]
//! asserts the **complete signal set** of each frame, not just the
//! signals the decoder happens to know about. An added signal is drift —
//! `tx_dropped` sat in the DBC unnoticed precisely because nothing
//! checked for arrivals, only for departures.
//!
//! **When this fails:** the ECU wire changed. Re-vendor `ecu.dbc` (see
//! `src/pit_diag/testdata/PROVENANCE.txt`), read the diff, and reconcile
//! `src/pit_diag/ecu.rs` — plus the CLI/Studio surfaces that carry the
//! new field — before shipping.

use can_dbc::{ByteOrder, Dbc, MessageId, ValueType};
use can_flasher::pit_diag::ecu::{
    self, ECU_ACK_ID, ECU_ARM_ID, ECU_BRAKE_ID, ECU_DV_ID, ECU_EXPECTED_FRAMES_PER_SCAN,
    ECU_FWINFO_ID, ECU_HEALTH_ID, ECU_INVERTER_ID, ECU_INVERTER_TEMPS_ID, ECU_INV_FAULTS_ID,
    ECU_PEDALS_ID, ECU_STATUS_ID,
};

const ECU_DBC: &str = include_str!(concat!(
    env!("CARGO_MANIFEST_DIR"),
    "/src/pit_diag/testdata/ecu.dbc"
));

fn load() -> Dbc {
    Dbc::try_from(ECU_DBC).expect("vendored ecu.dbc must parse")
}

fn msg_id_u32(id: &MessageId) -> u32 {
    match id {
        MessageId::Standard(s) => u32::from(*s),
        MessageId::Extended(e) => *e,
    }
}

fn message<'a>(dbc: &'a Dbc, name: &str) -> &'a can_dbc::Message {
    dbc.messages
        .iter()
        .find(|m| m.name == name)
        .unwrap_or_else(|| panic!("DBC has no message named {name:?} — ECU wire changed?"))
}

/// Every `PitDiag_*` message the ECU streams, paired with the decoder
/// constant that must sit at that ID. `PitDiag_cmd` / `PitDiag_ack` are
/// the arm handshake; the rest are the stream itself.
///
/// This table is the decoder's world-view. A `PitDiag_*` message in the
/// DBC that is missing here fails [`pit_diag_message_set_matches_the_decoder`]
/// — which is exactly what an added frame should do.
const KNOWN_PIT_DIAG_MESSAGES: &[(&str, u16)] = &[
    ("PitDiag_cmd", ECU_ARM_ID),
    ("PitDiag_ack", ECU_ACK_ID),
    ("PitDiag_status", ECU_STATUS_ID),
    ("PitDiag_pedals", ECU_PEDALS_ID),
    ("PitDiag_inverter", ECU_INVERTER_ID),
    ("PitDiag_fwinfo", ECU_FWINFO_ID),
    ("PitDiag_health", ECU_HEALTH_ID),
    ("PitDiag_brake", ECU_BRAKE_ID),
    ("PitDiag_inverter_temps", ECU_INVERTER_TEMPS_ID),
    ("PitDiag_dv", ECU_DV_ID),
    ("PitDiag_inv_faults", ECU_INV_FAULTS_ID),
];

/// `PitDiag_*` frames present upstream that this decoder does NOT yet
/// handle, with the issue tracking each.
///
/// This list exists so [`pit_diag_message_set_matches_the_decoder`] keeps
/// its teeth. Without it the choice is between failing forever on known
/// debt (which trains people to ignore the test) or widening the assertion
/// to "any message is fine" (which removes the guard entirely). Naming the
/// gaps keeps a genuinely NEW frame failing loudly while the known ones
/// stay greppable and attributable.
///
/// Adding an entry here is a deliberate act: anything in it is a frame the
/// tool silently drops on the floor.
const DEFERRED_PIT_DIAG_MESSAGES: &[(&str, &str)] = &[
    ("PitDiag_cell", "#566 - per-cell OCV/compensation detail"),
    ("PitDiag_pack_temp", "#566 - pack thermal derate detail"),
    (
        "PitDiag_inv_foc",
        "#566 - inverter FOC currents + control mode",
    ),
    (
        "PitDiag_inv_torque",
        "#566 - inverter torque request/estimate",
    ),
    ("PitDiag_power", "#566 - shaft/AC power + DC bus"),
];

// ---- Message set + IDs -------------------------------------------

#[test]
fn pit_diag_message_set_matches_the_decoder() {
    let dbc = load();

    let mut in_dbc: Vec<String> = dbc
        .messages
        .iter()
        .filter(|m| m.name.starts_with("PitDiag_"))
        .map(|m| m.name.clone())
        .collect();
    in_dbc.sort();

    let mut known: Vec<String> = KNOWN_PIT_DIAG_MESSAGES
        .iter()
        .map(|(n, _)| (*n).to_string())
        .chain(
            DEFERRED_PIT_DIAG_MESSAGES
                .iter()
                .map(|(n, _)| (*n).to_string()),
        )
        .collect();
    known.sort();

    assert_eq!(
        in_dbc, known,
        "the set of PitDiag_* messages changed. A NEW frame here means the \
         ECU started streaming something the decoder drops on the floor \
         (decode_frame returns None for unknown IDs, so the frames-per-scan \
         tally will NOT notice). Add it to src/pit_diag/ecu.rs and to \
         KNOWN_PIT_DIAG_MESSAGES."
    );
}

#[test]
fn pit_diag_ids_match_the_decoder() {
    let dbc = load();
    for (name, id) in KNOWN_PIT_DIAG_MESSAGES {
        assert_eq!(
            msg_id_u32(&message(&dbc, name).id),
            u32::from(*id),
            "{name} must sit at 0x{id:03X}"
        );
    }
}

#[test]
fn expected_frames_per_scan_counts_the_cyclic_stream() {
    // The cyclic (100 ms) stream is every PitDiag_* message except the
    // arm handshake and 0x704, which DiagTask emits at 1 Hz outside the
    // gate so it survives a ControlTask stall.
    let cyclic = KNOWN_PIT_DIAG_MESSAGES
        .iter()
        .filter(|(name, _)| !matches!(*name, "PitDiag_cmd" | "PitDiag_ack" | "PitDiag_health"))
        .count();
    assert_eq!(
        cyclic, ECU_EXPECTED_FRAMES_PER_SCAN,
        "ECU_EXPECTED_FRAMES_PER_SCAN must equal the number of cyclic \
         stream frames, or the scan-rate drift net silently mis-counts"
    );
}

#[test]
fn message_lengths_match_the_decoder_minimums() {
    let dbc = load();
    // (message, DLC the decoder assumes). `decode_frame` rejects payloads
    // shorter than these, so a DLC shrink upstream would make every frame
    // of that type silently vanish from the stream.
    let expected: &[(&str, u64)] = &[
        ("PitDiag_status", 8),
        ("PitDiag_pedals", 8),
        ("PitDiag_inverter", 8),
        ("PitDiag_fwinfo", 7),
        ("PitDiag_health", 8),
        ("PitDiag_brake", 3),
        ("PitDiag_inverter_temps", 7),
        ("PitDiag_dv", 8),
        ("PitDiag_inv_faults", 7),
    ];
    for (name, dlc) in expected {
        assert_eq!(
            message(&dbc, name).size,
            *dlc,
            "{name} DLC changed — decode_frame's length guard needs revisiting"
        );
    }
}

// ---- Full per-frame signal layout --------------------------------
//
// The strict one. Each entry is the COMPLETE signal set of a frame as
// (name, start_bit, size, big_endian, signed), mirroring the byte and
// bit offsets `decode_frame` hardcodes. Compared as a sorted set, so an
// added signal fails just as loudly as a moved or removed one.
//
// DBC convention: `@1` is little-endian/Intel (start_bit = LSB), `@0` is
// big-endian/Motorola (start_bit = MSB of the first byte).

type SigSpec = (&'static str, u64, u64, bool, bool);

fn layout(dbc: &Dbc, msg: &str) -> Vec<(String, u64, u64, bool, bool)> {
    let mut v: Vec<(String, u64, u64, bool, bool)> = message(dbc, msg)
        .signals
        .iter()
        .map(|s| {
            (
                s.name.clone(),
                s.start_bit,
                s.size,
                s.byte_order == ByteOrder::BigEndian,
                s.value_type == ValueType::Signed,
            )
        })
        .collect();
    v.sort_by(|a, b| a.0.cmp(&b.0));
    v
}

fn expect(specs: &[SigSpec]) -> Vec<(String, u64, u64, bool, bool)> {
    let mut v: Vec<(String, u64, u64, bool, bool)> = specs
        .iter()
        .map(|(n, start, size, be, signed)| ((*n).to_string(), *start, *size, *be, *signed))
        .collect();
    v.sort_by(|a, b| a.0.cmp(&b.0));
    v
}

#[test]
fn signal_layouts_match_the_decoder() {
    let dbc = load();

    // 0x700 — flags byte 2 carries seven bits; the decoder masks 0x01..0x40.
    assert_eq!(
        layout(&dbc, "PitDiag_status"),
        expect(&[
            ("fsm_state", 0, 8, false, false),
            ("inv_state", 8, 8, false, false),
            ("t11_8_9", 17, 1, false, false),
            ("rtds_active", 18, 1, false, false),
            ("ok_precharge", 19, 1, false, false),
            ("start_button", 20, 1, false, false),
            ("dv_mode", 21, 1, false, false),
            ("tx_dropped", 22, 1, false, false),
            ("power_capped", 23, 1, false, false),
            ("torque_pct", 24, 8, false, false),
            ("v_cell_min_mV", 39, 16, true, false),
            ("torque_cmd", 55, 16, true, true),
        ]),
        "0x700 layout drifted"
    );

    assert_eq!(
        layout(&dbc, "PitDiag_pedals"),
        expect(&[
            ("apps1_raw", 7, 16, true, false),
            ("apps2_raw", 23, 16, true, false),
            ("brake_raw", 39, 16, true, false),
            ("apps1_pct", 48, 8, false, false),
            ("apps2_pct", 56, 8, false, false),
        ]),
        "0x701 layout drifted"
    );

    // 0x702 — dem_present is bit 56 (byte 7 bit 0), inv_mode_cmd the
    // seven bits above it. The decoder reads byte 7 as `b & 1` / `b >> 1`.
    assert_eq!(
        layout(&dbc, "PitDiag_inverter"),
        expect(&[
            ("dc_bus_voltage", 7, 16, true, false),
            ("inv_rpm", 23, 32, true, true),
            ("inv_error", 48, 8, false, false),
            ("dem_present", 56, 1, false, false),
            ("inv_mode_cmd", 57, 7, false, false),
        ]),
        "0x702 layout drifted"
    );

    assert_eq!(
        layout(&dbc, "PitDiag_fwinfo"),
        expect(&[
            ("fw_major", 0, 8, false, false),
            ("fw_minor", 8, 8, false, false),
            ("fw_patch", 16, 8, false, false),
            ("git_hash", 31, 32, true, false),
        ]),
        "0x703 layout drifted"
    );

    // 0x704 — the frame that drifted twice. reset_cause is THREE bits at
    // 40 with stub_brake at 43; task_diag is bit 36, not 35.
    assert_eq!(
        layout(&dbc, "PitDiag_health"),
        expect(&[
            ("free_heap", 7, 16, true, false),
            ("min_free_heap", 23, 16, true, false),
            ("task_control", 32, 1, false, false),
            ("task_can_rx", 33, 1, false, false),
            ("task_can_tx", 34, 1, false, false),
            ("task_telemetry", 35, 1, false, false),
            ("task_diag", 36, 1, false, false),
            ("stub_no_ams", 37, 1, false, false),
            ("stub_no_inverter", 38, 1, false, false),
            ("stub_start", 39, 1, false, false),
            ("reset_cause", 40, 3, false, false),
            ("stub_brake", 43, 1, false, false),
            ("cal_status", 44, 2, false, false),
            ("stub_torque_cap", 46, 1, false, false),
            ("uptime_s", 48, 8, false, false),
            ("last_fault", 56, 8, false, false),
        ]),
        "0x704 layout drifted"
    );

    assert_eq!(
        layout(&dbc, "PitDiag_brake"),
        expect(&[
            ("brake_pressure", 7, 16, true, false),
            ("brake_pct", 16, 8, false, false),
        ]),
        "0x705 layout drifted"
    );

    assert_eq!(
        layout(&dbc, "PitDiag_inverter_temps"),
        expect(&[
            ("temp_board_degC", 0, 8, false, false),
            ("temp_pwrstg_degC", 8, 8, false, false),
            ("temp_motor1_degC", 16, 8, false, false),
            ("temp_motor2_degC", 24, 8, false, false),
            ("motor_temp_used_degC", 32, 8, false, false),
            ("thermal_cap_pct", 40, 8, false, false),
            ("temp_s1_valid", 48, 1, false, false),
            ("temp_s2_valid", 49, 1, false, false),
            ("temp_unknown", 50, 1, false, false),
            ("thermal_capped", 51, 1, false, false),
        ]),
        "0x706 layout drifted"
    );

    // 0x707 — motor_rpm_mech is LITTLE-endian signed here, unlike the
    // big-endian numerics elsewhere in the stream. Easy to get wrong.
    assert_eq!(
        layout(&dbc, "PitDiag_dv"),
        expect(&[
            ("dv_r2d_req", 0, 1, false, false),
            ("dv_cmd_fresh", 1, 1, false, false),
            ("ts_active", 2, 1, false, false),
            ("brake_over_limit", 3, 1, false, false),
            ("r2d_confirm", 4, 1, false, false),
            ("dv_torque_pct", 8, 8, false, false),
            ("motor_rpm_mech", 16, 16, false, true),
        ]),
        "0x707 layout drifted"
    );

    // 0x708 — two bitmask layers. L1 is nine bits, so it straddles a byte
    // boundary: bits 0-7 in byte 0 and bit 8 alone in byte 1. Getting that
    // ninth bit wrong silently loses OVP_Th2.
    assert_eq!(
        layout(&dbc, "PitDiag_inv_faults"),
        expect(&[
            ("pwrstg_alive", 0, 1, false, false),
            ("pwrstg_enable", 1, 1, false, false),
            ("pwrstg_uvlo", 2, 1, false, false),
            ("pwrstg_desat", 3, 1, false, false),
            ("pwrstg_dt_violation", 4, 1, false, false),
            ("pwrstg_hvil_open", 5, 1, false, false),
            ("pwrstg_ocp", 6, 1, false, false),
            ("pwrstg_ovp_th1", 7, 1, false, false),
            ("pwrstg_ovp_th2", 8, 1, false, false),
            ("emctrl_init_ok", 16, 1, false, false),
            ("emctrl_posfb", 17, 1, false, false),
            ("emctrl_asc", 18, 1, false, false),
            ("emctrl_curr_imbalance", 19, 1, false, false),
            ("emctrl_pwrstg_fault", 20, 1, false, false),
            ("emctrl_curr_derating", 21, 1, false, false),
            ("emctrl_loop_delocked", 22, 1, false, false),
            ("emctrl_phcurr_acq", 23, 1, false, false),
            ("cmd_follow_n", 24, 2, false, false),
            ("cmd_flt_clear", 26, 1, false, false),
            ("inv_state_age_ms", 32, 8, false, false),
            ("inv_state_seq", 40, 8, false, false),
            ("inv_redrive_count", 48, 8, false, false),
        ]),
        "0x708 layout drifted"
    );
}

// ---- Enum value tables -------------------------------------------

fn val_table(dbc: &Dbc, msg_id: u16, signal: &str) -> Vec<(i64, String)> {
    let mut v: Vec<(i64, String)> = dbc
        .value_descriptions_for_signal(MessageId::Standard(msg_id), signal)
        .unwrap_or_else(|| panic!("no VAL_ table for {signal} on 0x{msg_id:03X}"))
        .iter()
        .map(|d| (d.id, d.description.clone()))
        .collect();
    v.sort_by_key(|(id, _)| *id);
    v
}

fn table(pairs: &[(i64, &str)]) -> Vec<(i64, String)> {
    let mut v: Vec<(i64, String)> = pairs.iter().map(|(i, s)| (*i, (*s).to_string())).collect();
    v.sort_by_key(|(id, _)| *id);
    v
}

#[test]
fn fsm_state_value_table_matches_decoder() {
    let dbc = load();
    assert_eq!(
        val_table(&dbc, ECU_STATUS_ID, "fsm_state"),
        table(&[
            (0, "WaitInvVdcConfig"),
            (1, "Precharge"),
            (2, "WaitStartBrake"),
            (3, "R2dDelay"),
            (4, "WaitInvStandby"),
            (5, "Active"),
            (6, "AmsError"),
        ])
    );
}

/// The #528 headline: all seven, not the two the FSM gates on.
#[test]
fn inv_state_value_table_matches_decoder() {
    let dbc = load();
    let dbc_table = val_table(&dbc, ECU_STATUS_ID, "inv_state");
    assert_eq!(
        dbc_table,
        table(&[
            (0, "Off"),
            (3, "Standby"),
            (4, "Ready"),
            (6, "TorqueEnable"),
            (10, "SoftFault"),
            (11, "HardFault"),
            (13, "Shutdown"),
        ])
    );
    // And the decoder actually names every one of them — no silent
    // fall-through to Unknown, which is what #528 was reported for.
    for (raw, _) in &dbc_table {
        let decoded = ecu::EcuInvState::from_byte(u8::try_from(*raw).unwrap());
        assert!(
            !matches!(decoded, ecu::EcuInvState::Unknown(_)),
            "inv_state {raw} is named in the DBC but decodes to Unknown"
        );
    }
}

#[test]
fn inv_mode_cmd_value_table_matches_decoder() {
    let dbc = load();
    let dbc_table = val_table(&dbc, ECU_INVERTER_ID, "inv_mode_cmd");
    assert_eq!(
        dbc_table,
        table(&[
            (1, "Off"),
            (4, "Ready"),
            (6, "TorqueEnable"),
            (13, "HardFaultReset"),
            (19, "Fault"),
        ])
    );
    // Every commanded word the DBC names must round-trip through the
    // decoder's namer with the same spelling.
    for (raw, name) in &dbc_table {
        assert_eq!(
            ecu::inv_mode_cmd_name(u8::try_from(*raw).unwrap()),
            name,
            "inv_mode_cmd {raw} name drifted"
        );
    }
}

#[test]
fn inv_error_value_table_matches_decoder() {
    let dbc = load();
    let dbc_table = val_table(&dbc, ECU_INVERTER_ID, "inv_error");
    assert_eq!(dbc_table.len(), 16, "W90 §9.2.3 L3 table is codes 0..=15");
    for (raw, name) in &dbc_table {
        assert_eq!(
            ecu::dem_fault_name(u8::try_from(*raw).unwrap()),
            name,
            "DEM code {raw} name drifted"
        );
    }
    // Above the table the decoder must stay honest: "unknown", which the
    // surfaces render as *undocumented* rather than as a failed lookup.
    assert_eq!(ecu::dem_fault_name(16), "unknown");
}

#[test]
fn reset_cause_value_table_matches_decoder() {
    let dbc = load();
    let dbc_table = val_table(&dbc, ECU_HEALTH_ID, "reset_cause");
    assert_eq!(
        dbc_table,
        table(&[
            (0, "Unknown"),
            (1, "PowerOn"),
            (2, "Pin"),
            (3, "Software"),
            (4, "IWDG"),
            (5, "WWDG"),
            (6, "LowPower"),
        ])
    );
    // 3 bits hold 0..=7, and the DBC names 0..=6 — so only 7 may fall
    // through to Other. Anything else means the mask is wrong.
    for raw in 0u8..=6 {
        assert!(
            !matches!(
                ecu::EcuResetCause::from_byte(raw),
                ecu::EcuResetCause::Other(_)
            ),
            "reset_cause {raw} is named in the DBC but decodes to Other"
        );
    }
}

/// The 2-bit field is total — all four values are named, so the decoder
/// needs no fallback variant and must agree on every one.
#[test]
fn cal_status_value_table_matches_decoder() {
    let dbc = load();
    let dbc_table = val_table(&dbc, ECU_HEALTH_ID, "cal_status");
    assert_eq!(
        dbc_table,
        table(&[
            (0, "Defaults"),
            (1, "Loaded"),
            (2, "InvalidFellBack"),
            (3, "BadVersionFellBack"),
        ])
    );
    // Only "Loaded" means a stored calibration is actually in force; the
    // other three all leave the pedals on compile-time defaults.
    for (raw, name) in &dbc_table {
        let decoded = ecu::EcuCalStatus::from_bits(u8::try_from(*raw).unwrap());
        assert_eq!(
            decoded.is_fallback(),
            name != "Loaded",
            "cal_status {raw} ({name}) fallback classification"
        );
    }
}

#[test]
fn last_fault_value_table_is_the_sentinel_range() {
    let dbc = load();
    assert_eq!(
        val_table(&dbc, ECU_HEALTH_ID, "last_fault"),
        table(&[
            (0, "None"),
            (241, "HardFault"),
            (242, "MemManage"),
            (243, "BusFault"),
            (244, "UsageFault"),
            (245, "StackOverflow"),
            (246, "MallocFailed"),
            (247, "AssertFailed"),
        ])
    );
}
