//! Conformance test: the hardcoded ECU pit-diag decoder vs. the ECU DBC.
//!
//! Sibling of `pitdiag_dbc_conformance.rs`, which does the same job for
//! the AMS. `src/pit_diag/ecu.rs` decodes the ECU stream from a
//! **hardcoded** layout — fixed IDs, byte offsets, bit positions,
//! endianness and enum tables — against a wire that is generated from a
//! DSL in another repo (`IFS08-CE-ECU`, `Core/Inc/can/messages/*.def` →
//! `docs/dbc/ecu.dbc`, regenerated by their dbcinator bot).
//!
//! Nothing enforced that the two stayed in sync, and they didn't. By the
//! time #528 was filed, **six** drifts had accumulated silently:
//!
//! - `inv_mode_cmd` (`0x702` bits 57-63) never decoded at all;
//! - `EcuInvState` naming 2 of the 7 values the DSL defines, so every
//!   fault state rendered as `unknown(0x..)`;
//! - `0x704` `reset_cause` read as a whole byte after the firmware
//!   narrowed it to 3 bits, so a `stub_brake` board reported an
//!   impossible reset cause;
//! - `0x704` `task_diag` read at bit 3 after TelemetryTask took that bit,
//!   so the "diag alive" indicator showed the *telemetry* task;
//! - `0x704` bits 37-39 (the bench-stub announces) dropped entirely;
//! - `0x700` `tx_dropped` (bit 22) never decoded.
//!
//! The first five were fixed in v2.9.0 by hand. This test is what makes
//! the *next* one loud, and it is deliberately stricter than the AMS
//! sibling in one way that matters: [`signal_layouts_match_the_decoder`]
//! asserts the **complete signal set** of each frame, not just the
//! signals the decoder happens to know about. An added signal is drift —
//! `tx_dropped` sat in the DBC unnoticed precisely because nothing
//! checked for arrivals, only for departures.
//!
//! **When this fails:** the ECU wire changed. Re-vendor `ecu.dbc` (see
//! `src/pit_diag/testdata/PROVENANCE.txt`), read the diff, and reconcile
//! `src/pit_diag/ecu.rs` — plus the CLI/Studio surfaces that carry the
//! new field — before shipping.

use can_dbc::{ByteOrder, Dbc, MessageId, ValueType};
use can_flasher::pit_diag::ecu::{
    self, EcuPitDiagFrame, ECU_ACK_ID, ECU_ARM_ID, ECU_BRAKE_ID, ECU_CELL_ID, ECU_DV_ID,
    ECU_EXPECTED_FRAMES_PER_SCAN, ECU_FWINFO_ID, ECU_HEALTH_ID, ECU_INVERTER_ID,
    ECU_INVERTER_TEMPS_ID, ECU_INV_FAULTS_ID, ECU_INV_FOC_ID, ECU_INV_TORQUE_ID, ECU_PACK_TEMP_ID,
    ECU_PEDALS_ID, ECU_POWER_ID, ECU_STATUS_ID,
};
use can_flasher::protocol::CanFrame;

const ECU_DBC: &str = include_str!(concat!(
    env!("CARGO_MANIFEST_DIR"),
    "/src/pit_diag/testdata/ecu.dbc"
));

fn load() -> Dbc {
    Dbc::try_from(ECU_DBC).expect("vendored ecu.dbc must parse")
}

fn msg_id_u32(id: &MessageId) -> u32 {
    match id {
        MessageId::Standard(s) => u32::from(*s),
        MessageId::Extended(e) => *e,
    }
}

fn message<'a>(dbc: &'a Dbc, name: &str) -> &'a can_dbc::Message {
    dbc.messages
        .iter()
        .find(|m| m.name == name)
        .unwrap_or_else(|| panic!("DBC has no message named {name:?} — ECU wire changed?"))
}

/// Every `PitDiag_*` message the ECU streams, paired with the decoder
/// constant that must sit at that ID. `PitDiag_cmd` / `PitDiag_ack` are
/// the arm handshake; the rest are the stream itself.
///
/// This table is the decoder's world-view. A `PitDiag_*` message in the
/// DBC that is missing here fails [`pit_diag_message_set_matches_the_decoder`]
/// — which is exactly what an added frame should do.
const KNOWN_PIT_DIAG_MESSAGES: &[(&str, u16)] = &[
    ("PitDiag_cmd", ECU_ARM_ID),
    ("PitDiag_ack", ECU_ACK_ID),
    ("PitDiag_status", ECU_STATUS_ID),
    ("PitDiag_pedals", ECU_PEDALS_ID),
    ("PitDiag_inverter", ECU_INVERTER_ID),
    ("PitDiag_fwinfo", ECU_FWINFO_ID),
    ("PitDiag_health", ECU_HEALTH_ID),
    ("PitDiag_brake", ECU_BRAKE_ID),
    ("PitDiag_inverter_temps", ECU_INVERTER_TEMPS_ID),
    ("PitDiag_dv", ECU_DV_ID),
    ("PitDiag_inv_faults", ECU_INV_FAULTS_ID),
    ("PitDiag_cell", ECU_CELL_ID),
    ("PitDiag_pack_temp", ECU_PACK_TEMP_ID),
    ("PitDiag_inv_foc", ECU_INV_FOC_ID),
    ("PitDiag_inv_torque", ECU_INV_TORQUE_ID),
    ("PitDiag_power", ECU_POWER_ID),
];

/// `PitDiag_*` frames present upstream that this decoder does NOT yet
/// handle, with the issue tracking each.
///
/// This list exists so [`pit_diag_message_set_matches_the_decoder`] keeps
/// its teeth. Without it the choice is between failing forever on known
/// debt (which trains people to ignore the test) or widening the assertion
/// to "any message is fine" (which removes the guard entirely). Naming the
/// gaps keeps a genuinely NEW frame failing loudly while the known ones
/// stay greppable and attributable.
///
/// Adding an entry here is a deliberate act: anything in it is a frame the
/// tool silently drops on the floor.
const DEFERRED_PIT_DIAG_MESSAGES: &[(&str, &str)] = &[];

// ---- Message set + IDs -------------------------------------------

#[test]
fn pit_diag_message_set_matches_the_decoder() {
    let dbc = load();

    let mut in_dbc: Vec<String> = dbc
        .messages
        .iter()
        .filter(|m| m.name.starts_with("PitDiag_"))
        .map(|m| m.name.clone())
        .collect();
    in_dbc.sort();

    let mut known: Vec<String> = KNOWN_PIT_DIAG_MESSAGES
        .iter()
        .map(|(n, _)| (*n).to_string())
        .chain(
            DEFERRED_PIT_DIAG_MESSAGES
                .iter()
                .map(|(n, _)| (*n).to_string()),
        )
        .collect();
    known.sort();

    assert_eq!(
        in_dbc, known,
        "the set of PitDiag_* messages changed. A NEW frame here means the \
         ECU started streaming something the decoder drops on the floor \
         (decode_frame returns None for unknown IDs, so the frames-per-scan \
         tally will NOT notice). Add it to src/pit_diag/ecu.rs and to \
         KNOWN_PIT_DIAG_MESSAGES."
    );
}

#[test]
fn pit_diag_ids_match_the_decoder() {
    let dbc = load();
    for (name, id) in KNOWN_PIT_DIAG_MESSAGES {
        assert_eq!(
            msg_id_u32(&message(&dbc, name).id),
            u32::from(*id),
            "{name} must sit at 0x{id:03X}"
        );
    }
}

#[test]
fn expected_frames_per_scan_counts_the_cyclic_stream() {
    // The cyclic (100 ms) stream is every PitDiag_* message except the
    // arm handshake and 0x704, which DiagTask emits at 1 Hz outside the
    // gate so it survives a ControlTask stall.
    let cyclic = KNOWN_PIT_DIAG_MESSAGES
        .iter()
        .filter(|(name, _)| !matches!(*name, "PitDiag_cmd" | "PitDiag_ack" | "PitDiag_health"))
        .count();
    assert_eq!(
        cyclic, ECU_EXPECTED_FRAMES_PER_SCAN,
        "ECU_EXPECTED_FRAMES_PER_SCAN must equal the number of cyclic \
         stream frames, or the scan-rate drift net silently mis-counts"
    );
}

#[test]
fn message_lengths_match_the_decoder_minimums() {
    let dbc = load();
    // (message, DLC the decoder assumes). `decode_frame` rejects payloads
    // shorter than these, so a DLC shrink upstream would make every frame
    // of that type silently vanish from the stream.
    let expected: &[(&str, u64)] = &[
        ("PitDiag_status", 8),
        ("PitDiag_pedals", 8),
        ("PitDiag_inverter", 8),
        ("PitDiag_fwinfo", 7),
        ("PitDiag_health", 8),
        ("PitDiag_brake", 3),
        ("PitDiag_inverter_temps", 7),
        ("PitDiag_dv", 8),
        ("PitDiag_inv_faults", 7),
        ("PitDiag_cell", 8),
        ("PitDiag_pack_temp", 6),
        ("PitDiag_inv_foc", 8),
        ("PitDiag_inv_torque", 8),
        ("PitDiag_power", 8),
    ];
    for (name, dlc) in expected {
        assert_eq!(
            message(&dbc, name).size,
            *dlc,
            "{name} DLC changed — decode_frame's length guard needs revisiting"
        );
    }
}

// ---- Full per-frame signal layout --------------------------------
//
// The strict one. Each entry is the COMPLETE signal set of a frame as
// (name, start_bit, size, big_endian, signed), mirroring the byte and
// bit offsets `decode_frame` hardcodes. Compared as a sorted set, so an
// added signal fails just as loudly as a moved or removed one.
//
// DBC convention: `@1` is little-endian/Intel (start_bit = LSB), `@0` is
// big-endian/Motorola (start_bit = MSB of the first byte).

type SigSpec = (&'static str, u64, u64, bool, bool);

fn layout(dbc: &Dbc, msg: &str) -> Vec<(String, u64, u64, bool, bool)> {
    let mut v: Vec<(String, u64, u64, bool, bool)> = message(dbc, msg)
        .signals
        .iter()
        .map(|s| {
            (
                s.name.clone(),
                s.start_bit,
                s.size,
                s.byte_order == ByteOrder::BigEndian,
                s.value_type == ValueType::Signed,
            )
        })
        .collect();
    v.sort_by(|a, b| a.0.cmp(&b.0));
    v
}

fn expect(specs: &[SigSpec]) -> Vec<(String, u64, u64, bool, bool)> {
    let mut v: Vec<(String, u64, u64, bool, bool)> = specs
        .iter()
        .map(|(n, start, size, be, signed)| ((*n).to_string(), *start, *size, *be, *signed))
        .collect();
    v.sort_by(|a, b| a.0.cmp(&b.0));
    v
}

#[test]
fn signal_layouts_match_the_decoder() {
    let dbc = load();

    // 0x700 — flags byte 2 carries seven bits; the decoder masks 0x01..0x40.
    assert_eq!(
        layout(&dbc, "PitDiag_status"),
        expect(&[
            ("fsm_state", 0, 8, false, false),
            ("inv_state", 8, 8, false, false),
            ("t11_8_9", 17, 1, false, false),
            ("rtds_active", 18, 1, false, false),
            ("ok_precharge", 19, 1, false, false),
            ("start_button", 20, 1, false, false),
            ("dv_mode", 21, 1, false, false),
            ("tx_dropped", 22, 1, false, false),
            ("power_capped", 23, 1, false, false),
            ("torque_pct", 24, 8, false, false),
            ("v_cell_min_mV", 39, 16, true, false),
            ("torque_cmd", 55, 16, true, true),
        ]),
        "0x700 layout drifted"
    );

    assert_eq!(
        layout(&dbc, "PitDiag_pedals"),
        expect(&[
            ("apps1_raw", 7, 16, true, false),
            ("apps2_raw", 23, 16, true, false),
            ("brake_raw", 39, 16, true, false),
            ("apps1_pct", 48, 8, false, false),
            ("apps2_pct", 56, 8, false, false),
        ]),
        "0x701 layout drifted"
    );

    // 0x702 — dem_present is bit 56 (byte 7 bit 0), inv_mode_cmd the
    // seven bits above it. The decoder reads byte 7 as `b & 1` / `b >> 1`.
    assert_eq!(
        layout(&dbc, "PitDiag_inverter"),
        expect(&[
            ("dc_bus_voltage", 7, 16, true, false),
            ("inv_rpm", 23, 32, true, true),
            ("inv_error", 48, 8, false, false),
            ("dem_present", 56, 1, false, false),
            ("inv_mode_cmd", 57, 7, false, false),
        ]),
        "0x702 layout drifted"
    );

    assert_eq!(
        layout(&dbc, "PitDiag_fwinfo"),
        expect(&[
            ("fw_major", 0, 8, false, false),
            ("fw_minor", 8, 8, false, false),
            ("fw_patch", 16, 8, false, false),
            ("git_hash", 31, 32, true, false),
        ]),
        "0x703 layout drifted"
    );

    // 0x704 — the frame that drifted twice. reset_cause is THREE bits at
    // 40 with stub_brake at 43; task_diag is bit 36, not 35.
    assert_eq!(
        layout(&dbc, "PitDiag_health"),
        expect(&[
            ("free_heap", 7, 16, true, false),
            ("min_free_heap", 23, 16, true, false),
            ("task_control", 32, 1, false, false),
            ("task_can_rx", 33, 1, false, false),
            ("task_can_tx", 34, 1, false, false),
            ("task_telemetry", 35, 1, false, false),
            ("task_diag", 36, 1, false, false),
            ("stub_no_ams", 37, 1, false, false),
            ("stub_no_inverter", 38, 1, false, false),
            ("stub_start", 39, 1, false, false),
            ("reset_cause", 40, 3, false, false),
            ("stub_brake", 43, 1, false, false),
            ("cal_status", 44, 2, false, false),
            ("stub_torque_cap", 46, 1, false, false),
            ("boot_refused", 47, 1, false, false),
            ("uptime_s", 48, 8, false, false),
            ("last_fault", 56, 8, false, false),
        ]),
        "0x704 layout drifted"
    );

    assert_eq!(
        layout(&dbc, "PitDiag_brake"),
        expect(&[
            ("brake_pressure", 7, 16, true, false),
            ("brake_pct", 16, 8, false, false),
        ]),
        "0x705 layout drifted"
    );

    assert_eq!(
        layout(&dbc, "PitDiag_inverter_temps"),
        expect(&[
            ("temp_board_degC", 0, 8, false, false),
            ("temp_pwrstg_degC", 8, 8, false, false),
            ("temp_motor1_degC", 16, 8, false, false),
            ("temp_motor2_degC", 24, 8, false, false),
            ("motor_temp_used_degC", 32, 8, false, false),
            ("thermal_cap_pct", 40, 8, false, false),
            ("temp_s1_valid", 48, 1, false, false),
            ("temp_s2_valid", 49, 1, false, false),
            ("temp_unknown", 50, 1, false, false),
            ("thermal_capped", 51, 1, false, false),
        ]),
        "0x706 layout drifted"
    );

    // 0x707 — motor_rpm_mech is LITTLE-endian signed here, unlike the
    // big-endian numerics elsewhere in the stream. Easy to get wrong.
    assert_eq!(
        layout(&dbc, "PitDiag_dv"),
        expect(&[
            ("dv_r2d_req", 0, 1, false, false),
            ("dv_cmd_fresh", 1, 1, false, false),
            ("ts_active", 2, 1, false, false),
            ("brake_over_limit", 3, 1, false, false),
            ("r2d_confirm", 4, 1, false, false),
            ("as_emergency", 5, 1, false, false),
            ("as_from_stale", 6, 1, false, false),
            ("as_fresh", 7, 1, false, false),
            ("dv_torque_pct", 8, 8, false, false),
            ("motor_rpm_mech", 16, 16, false, true),
            ("as_status", 32, 8, false, false),
        ]),
        "0x707 layout drifted"
    );

    // 0x708 — two bitmask layers. L1 is nine bits, so it straddles a byte
    // boundary: bits 0-7 in byte 0 and bit 8 alone in byte 1. Getting that
    // ninth bit wrong silently loses OVP_Th2.
    assert_eq!(
        layout(&dbc, "PitDiag_inv_faults"),
        expect(&[
            ("pwrstg_alive", 0, 1, false, false),
            ("pwrstg_enable", 1, 1, false, false),
            ("pwrstg_uvlo", 2, 1, false, false),
            ("pwrstg_desat", 3, 1, false, false),
            ("pwrstg_dt_violation", 4, 1, false, false),
            ("pwrstg_hvil_open", 5, 1, false, false),
            ("pwrstg_ocp", 6, 1, false, false),
            ("pwrstg_ovp_th1", 7, 1, false, false),
            ("pwrstg_ovp_th2", 8, 1, false, false),
            ("emctrl_init_ok", 16, 1, false, false),
            ("emctrl_posfb", 17, 1, false, false),
            ("emctrl_asc", 18, 1, false, false),
            ("emctrl_curr_imbalance", 19, 1, false, false),
            ("emctrl_pwrstg_fault", 20, 1, false, false),
            ("emctrl_curr_derating", 21, 1, false, false),
            ("emctrl_loop_delocked", 22, 1, false, false),
            ("emctrl_phcurr_acq", 23, 1, false, false),
            ("cmd_follow_n", 24, 2, false, false),
            ("cmd_flt_clear", 26, 1, false, false),
            ("inv_state_age_ms", 32, 8, false, false),
            ("inv_state_seq", 40, 8, false, false),
            ("inv_redrive_count", 48, 8, false, false),
        ]),
        "0x708 layout drifted"
    );

    // 0x709 — Motorola 16-bit fields (start = MSB of the first byte).
    assert_eq!(
        layout(&dbc, "PitDiag_cell"),
        expect(&[
            ("raw_mV", 7, 16, true, false),
            ("est_ocv_mV", 23, 16, true, false),
            ("comp_mV", 39, 16, true, true),
            ("cap_pct", 48, 8, false, false),
            ("compensated", 56, 1, false, false),
            ("raw_floor", 57, 1, false, false),
            ("capped", 58, 1, false, false),
        ]),
        "0x709 layout drifted"
    );

    // 0x70A — Motorola signed temperatures; module mask + status in byte 5.
    assert_eq!(
        layout(&dbc, "PitDiag_pack_temp"),
        expect(&[
            ("pack_temp_used_degC", 7, 16, true, true),
            ("pack_temp_raw_degC", 23, 16, true, true),
            ("pack_cap_pct", 32, 8, false, false),
            ("mod0_used", 40, 1, false, false),
            ("mod1_used", 41, 1, false, false),
            ("mod2_used", 42, 1, false, false),
            ("mod3_used", 43, 1, false, false),
            ("mod4_used", 44, 1, false, false),
            ("pack_unknown", 45, 1, false, false),
            ("pack_capped", 46, 1, false, false),
        ]),
        "0x70A layout drifted"
    );

    // 0x70B — Intel throughout; three 4-bit enums packed two per byte.
    assert_eq!(
        layout(&dbc, "PitDiag_inv_foc"),
        expect(&[
            ("current_d_A", 0, 16, false, true),
            ("current_q_A", 16, 16, false, true),
            ("volt_modulus", 32, 16, false, false),
            ("ctrl_mode", 48, 4, false, false),
            ("ctrl_type", 52, 4, false, false),
            ("cmd_src", 56, 4, false, false),
            ("s4_fresh", 60, 1, false, false),
            ("s6_fresh", 61, 1, false, false),
            ("s8_fresh", 62, 1, false, false),
            ("s9_fresh", 63, 1, false, false),
        ]),
        "0x70B layout drifted"
    );

    // 0x70C — four signed Intel 16-bit fields.
    assert_eq!(
        layout(&dbc, "PitDiag_inv_torque"),
        expect(&[
            ("torque_req", 0, 16, false, true),
            ("torque_max_feas", 16, 16, false, true),
            ("torque_est", 32, 16, false, true),
            ("setpoint_q", 48, 16, false, true),
        ]),
        "0x70C layout drifted"
    );

    // 0x70D — Intel; dc_bus_V is the only unsigned field.
    assert_eq!(
        layout(&dbc, "PitDiag_power"),
        expect(&[
            ("shaft_power", 0, 16, false, true),
            ("ac_power", 16, 16, false, true),
            ("dc_bus_V", 32, 16, false, false),
            ("accu_current", 48, 16, false, true),
        ]),
        "0x70D layout drifted"
    );
}

// ---- DBC-driven round trip ---------------------------------------
//
// The layout test above compares the DBC against a hand-written list, and
// the unit tests in ecu.rs check the decoder against hand-built bytes —
// neither ties the decoder to the DBC's bit positions directly. For frames
// that mix Motorola and Intel fields that gap is where a byte-order bug
// hides. So: pack raw signal values into a frame using ONLY the DBC's own
// start bit / size / byte order / scale, run it through `decode_frame`,
// and check every field comes back.

/// Set `value` (two's complement, low `size` bits) into `data` at a DBC
/// signal position. Intel: `start` is the LSB, bits ascend. Motorola:
/// `start` is the MSB and bits walk the DBC "sawtooth" (down within a
/// byte, then to bit 7 of the next byte).
fn put_signal(data: &mut [u8; 8], sig: &can_dbc::Signal, value: i64) {
    let size = sig.size as i64;
    let bit_of = |i: i64| (value >> i) & 1 == 1;
    match sig.byte_order {
        ByteOrder::LittleEndian => {
            for i in 0..size {
                let pos = sig.start_bit as i64 + i;
                if bit_of(i) {
                    data[(pos / 8) as usize] |= 1 << (pos % 8);
                }
            }
        }
        ByteOrder::BigEndian => {
            let mut pos = sig.start_bit as i64;
            for i in (0..size).rev() {
                if bit_of(i) {
                    data[(pos / 8) as usize] |= 1 << (pos % 8);
                }
                pos = if pos % 8 == 0 { pos + 15 } else { pos - 1 };
            }
        }
    }
}

/// Pack a whole message from `(signal, physical value)` pairs, converting
/// through the DBC's own factor so a scale mismatch fails too.
fn pack(dbc: &Dbc, msg: &str, values: &[(&str, f64)]) -> CanFrame {
    let m = message(dbc, msg);
    assert_eq!(
        m.signals.len(),
        values.len(),
        "{msg}: give a value for every signal so none goes untested"
    );
    let mut data = [0u8; 8];
    for (name, phys) in values {
        let sig = m
            .signals
            .iter()
            .find(|s| s.name == *name)
            .unwrap_or_else(|| panic!("{msg} has no signal {name}"));
        let raw = ((phys - sig.offset) / sig.factor).round() as i64;
        put_signal(&mut data, sig, raw);
    }
    let id = msg_id_u32(&m.id) as u16;
    CanFrame::new(id, &data[..m.size as usize]).unwrap()
}

#[test]
fn new_frames_round_trip_through_the_dbc_encoding() {
    let dbc = load();

    // Values chosen so every 16-bit field has distinct high/low bytes
    // (a byte-swap can't pass by symmetry) and signed fields go negative.
    let f = pack(
        &dbc,
        "PitDiag_cell",
        &[
            ("raw_mV", 3412.0),
            ("est_ocv_mV", 3587.0),
            ("comp_mV", -175.0),
            ("cap_pct", 64.0),
            ("compensated", 1.0),
            ("raw_floor", 0.0),
            ("capped", 1.0),
        ],
    );
    match ecu::decode_frame(&f).expect("0x709 decodes") {
        EcuPitDiagFrame::Cell(c) => {
            assert_eq!(
                (c.raw_mv, c.est_ocv_mv, c.comp_mv, c.cap_pct),
                (3412, 3587, -175, 64)
            );
            assert_eq!((c.compensated, c.raw_floor, c.capped), (true, false, true));
        }
        other => panic!("0x709 decoded as {other:?}"),
    }

    let f = pack(
        &dbc,
        "PitDiag_pack_temp",
        &[
            ("pack_temp_used_degC", 47.0),
            ("pack_temp_raw_degC", -12.0),
            ("pack_cap_pct", 83.0),
            ("mod0_used", 1.0),
            ("mod1_used", 0.0),
            ("mod2_used", 1.0),
            ("mod3_used", 1.0),
            ("mod4_used", 0.0),
            ("pack_unknown", 0.0),
            ("pack_capped", 1.0),
        ],
    );
    match ecu::decode_frame(&f).expect("0x70A decodes") {
        EcuPitDiagFrame::PackTemp(t) => {
            assert_eq!(
                (t.pack_temp_used_degc, t.pack_temp_raw_degc, t.pack_cap_pct),
                (47, -12, 83)
            );
            assert_eq!(t.modules_used, [true, false, true, true, false]);
            assert_eq!((t.pack_unknown, t.pack_capped), (false, true));
        }
        other => panic!("0x70A decoded as {other:?}"),
    }

    let f = pack(
        &dbc,
        "PitDiag_inv_foc",
        &[
            ("current_d_A", -42.5),
            ("current_q_A", 187.25),
            ("volt_modulus", 947.0),
            ("ctrl_mode", 3.0),
            ("ctrl_type", 10.0),
            ("cmd_src", 6.0),
            ("s4_fresh", 1.0),
            ("s6_fresh", 0.0),
            ("s8_fresh", 1.0),
            ("s9_fresh", 1.0),
        ],
    );
    match ecu::decode_frame(&f).expect("0x70B decodes") {
        EcuPitDiagFrame::InvFoc(r) => {
            assert_eq!((r.current_d_a(), r.current_q_a()), (-42.5, 187.25));
            assert_eq!(r.volt_modulus_permil, 947);
            assert_eq!((r.ctrl_mode, r.ctrl_type, r.cmd_src), (3, 10, 6));
            assert_eq!(
                (r.s4_fresh, r.s6_fresh, r.s8_fresh, r.s9_fresh),
                (true, false, true, true)
            );
        }
        other => panic!("0x70B decoded as {other:?}"),
    }

    let f = pack(
        &dbc,
        "PitDiag_inv_torque",
        &[
            ("torque_req", -123.0),
            ("torque_max_feas", 1450.0),
            ("torque_est", -118.0),
            ("setpoint_q", -96.5),
        ],
    );
    match ecu::decode_frame(&f).expect("0x70C decodes") {
        EcuPitDiagFrame::InvTorque(t) => {
            assert_eq!(
                (t.torque_req_nm, t.torque_max_feas_raw, t.torque_est_nm),
                (-123, 1450, -118)
            );
            assert_eq!(t.setpoint_q_a(), -96.5);
        }
        other => panic!("0x70C decoded as {other:?}"),
    }

    let f = pack(
        &dbc,
        "PitDiag_power",
        &[
            ("shaft_power", 71_230.0),
            ("ac_power", -5_430.0),
            ("dc_bus_V", 561.0),
            ("accu_current", -134.7),
        ],
    );
    match ecu::decode_frame(&f).expect("0x70D decodes") {
        EcuPitDiagFrame::Power(w) => {
            assert_eq!(
                (w.shaft_power_w(), w.ac_power_w(), w.dc_bus_v),
                (71_230, -5_430, 561)
            );
            assert_eq!(w.accu_current_raw, -1347);
        }
        other => panic!("0x70D decoded as {other:?}"),
    }
}

// ---- Enum value tables -------------------------------------------

/// `UDV_as_status` (1290 / `0x50A`) — a uDV bus message, not a pit-diag frame.
/// It is referenced here only because it owns the `VAL_` table for the
/// `as_status` byte the ECU mirrors into `PitDiag_dv`.
const UDV_AS_STATUS_ID: u16 = 0x50A;

fn val_table(dbc: &Dbc, msg_id: u16, signal: &str) -> Vec<(i64, String)> {
    let mut v: Vec<(i64, String)> = dbc
        .value_descriptions_for_signal(MessageId::Standard(msg_id), signal)
        .unwrap_or_else(|| panic!("no VAL_ table for {signal} on 0x{msg_id:03X}"))
        .iter()
        .map(|d| (d.id, d.description.clone()))
        .collect();
    v.sort_by_key(|(id, _)| *id);
    v
}

fn table(pairs: &[(i64, &str)]) -> Vec<(i64, String)> {
    let mut v: Vec<(i64, String)> = pairs.iter().map(|(i, s)| (*i, (*s).to_string())).collect();
    v.sort_by_key(|(id, _)| *id);
    v
}

#[test]
fn fsm_state_value_table_matches_decoder() {
    let dbc = load();
    assert_eq!(
        val_table(&dbc, ECU_STATUS_ID, "fsm_state"),
        table(&[
            (0, "WaitInvVdcConfig"),
            (1, "Precharge"),
            (2, "WaitStartBrake"),
            (3, "R2dDelay"),
            (4, "WaitInvStandby"),
            (5, "Active"),
            (6, "AmsError"),
        ])
    );
}

/// The #528 headline: all seven, not the two the FSM gates on.
#[test]
fn inv_state_value_table_matches_decoder() {
    let dbc = load();
    let dbc_table = val_table(&dbc, ECU_STATUS_ID, "inv_state");
    assert_eq!(
        dbc_table,
        table(&[
            (0, "Off"),
            (3, "Standby"),
            (4, "Ready"),
            (6, "TorqueEnable"),
            (10, "SoftFault"),
            (11, "HardFault"),
            (13, "Shutdown"),
        ])
    );
    // And the decoder actually names every one of them — no silent
    // fall-through to Unknown, which is what #528 was reported for.
    for (raw, _) in &dbc_table {
        let decoded = ecu::EcuInvState::from_byte(u8::try_from(*raw).unwrap());
        assert!(
            !matches!(decoded, ecu::EcuInvState::Unknown(_)),
            "inv_state {raw} is named in the DBC but decodes to Unknown"
        );
    }
}

#[test]
fn inv_mode_cmd_value_table_matches_decoder() {
    let dbc = load();
    let dbc_table = val_table(&dbc, ECU_INVERTER_ID, "inv_mode_cmd");
    assert_eq!(
        dbc_table,
        table(&[
            (1, "Off"),
            (4, "Ready"),
            (6, "TorqueEnable"),
            (13, "HardFaultReset"),
            (19, "Fault"),
        ])
    );
    // Every commanded word the DBC names must round-trip through the
    // decoder's namer with the same spelling.
    for (raw, name) in &dbc_table {
        assert_eq!(
            ecu::inv_mode_cmd_name(u8::try_from(*raw).unwrap()),
            name,
            "inv_mode_cmd {raw} name drifted"
        );
    }
}

#[test]
fn inv_error_value_table_matches_decoder() {
    let dbc = load();
    let dbc_table = val_table(&dbc, ECU_INVERTER_ID, "inv_error");
    assert_eq!(dbc_table.len(), 16, "W90 §9.2.3 L3 table is codes 0..=15");
    for (raw, name) in &dbc_table {
        assert_eq!(
            ecu::dem_fault_name(u8::try_from(*raw).unwrap()),
            name,
            "DEM code {raw} name drifted"
        );
    }
    // Above the table the decoder must stay honest: "unknown", which the
    // surfaces render as *undocumented* rather than as a failed lookup.
    assert_eq!(ecu::dem_fault_name(16), "unknown");
}

#[test]
fn reset_cause_value_table_matches_decoder() {
    let dbc = load();
    let dbc_table = val_table(&dbc, ECU_HEALTH_ID, "reset_cause");
    assert_eq!(
        dbc_table,
        table(&[
            (0, "Unknown"),
            (1, "PowerOn"),
            (2, "Pin"),
            (3, "Software"),
            (4, "IWDG"),
            (5, "WWDG"),
            (6, "LowPower"),
        ])
    );
    // 3 bits hold 0..=7, and the DBC names 0..=6 — so only 7 may fall
    // through to Other. Anything else means the mask is wrong.
    for raw in 0u8..=6 {
        assert!(
            !matches!(
                ecu::EcuResetCause::from_byte(raw),
                ecu::EcuResetCause::Other(_)
            ),
            "reset_cause {raw} is named in the DBC but decodes to Other"
        );
    }
}

/// The 2-bit field is total — all four values are named, so the decoder
/// needs no fallback variant and must agree on every one.
#[test]
fn cal_status_value_table_matches_decoder() {
    let dbc = load();
    let dbc_table = val_table(&dbc, ECU_HEALTH_ID, "cal_status");
    assert_eq!(
        dbc_table,
        table(&[
            (0, "Defaults"),
            (1, "Loaded"),
            (2, "InvalidFellBack"),
            (3, "BadVersionFellBack"),
        ])
    );
    // Only "Loaded" means a stored calibration is actually in force; the
    // other three all leave the pedals on compile-time defaults.
    for (raw, name) in &dbc_table {
        let decoded = ecu::EcuCalStatus::from_bits(u8::try_from(*raw).unwrap());
        assert_eq!(
            decoded.is_fallback(),
            name != "Loaded",
            "cal_status {raw} ({name}) fallback classification"
        );
    }
}

/// `as_status` is the one decoder enum whose value table does **not** live
/// on the message that carries it. `PitDiag_dv` declares the signal with no
/// `VAL_` of its own — the ECU is mirroring a byte the uDV owns, and the names
/// are published once, on `UDV_as_status` (`0x50A`).
///
/// That indirection is exactly why this test exists. Nothing about
/// `PitDiag_dv` changes if the uDV renumbers the enum, so a decoder that
/// hardcoded the labels from the ECU's frame alone would drift silently and
/// the layout assertions above would keep passing.
#[test]
fn as_status_value_table_matches_decoder() {
    let dbc = load();
    let dbc_table = val_table(&dbc, UDV_AS_STATUS_ID, "as_status");
    assert_eq!(
        dbc_table,
        table(&[
            (0, "Off"),
            (1, "Emergency"),
            (2, "Ready"),
            (3, "Driving"),
            (4, "Finished"),
        ])
    );
    for (raw, name) in &dbc_table {
        let decoded = ecu::EcuAsStatus::from_byte(u8::try_from(*raw).unwrap());
        assert!(
            !matches!(decoded, ecu::EcuAsStatus::Other(_)),
            "as_status {raw} ({name}) is named in the DBC but decodes to Other"
        );
        assert_eq!(
            decoded.as_str(),
            name.to_lowercase(),
            "as_status {raw} label drifted"
        );
    }
    // The field is a full byte and the DBC names only 0..=4, so everything
    // above must fall through rather than aliasing onto a real state.
    assert_eq!(ecu::EcuAsStatus::from_byte(5), ecu::EcuAsStatus::Other(5));
    assert_eq!(ecu::EcuAsStatus::from_byte(0xFF).as_str(), "unknown");
}

#[test]
fn last_fault_value_table_is_the_sentinel_range() {
    let dbc = load();
    assert_eq!(
        val_table(&dbc, ECU_HEALTH_ID, "last_fault"),
        table(&[
            (0, "None"),
            (241, "HardFault"),
            (242, "MemManage"),
            (243, "BusFault"),
            (244, "UsageFault"),
            (245, "StackOverflow"),
            (246, "MallocFailed"),
            (247, "AssertFailed"),
        ])
    );
}
